swears = [
    '1. Arse, arsehole – n., variants of ass and asshole. Can also be used to mean bothered ("Can\'t be arsed") or acting the fool ("Stop arsing about!"). Mild.',
    '2. Bastard – n., illegitimate child or mongrel; objectionable fellow, probably one who has won one over on you; unpleasant situation ("I\'m having a bastard of a morning!"). See also: git, rotter, swine.',
    '3. Bell, bellend – n., head of a penis; fool. (Only write as "bell end" if referring to the end of an actual bell.) Medium strength. See also: dickhead, knobend.',
    '4. Berk – n., idiot. Very mild, yet apparently originated as rhyming slang for "Berkeley hunt".',
    '5. Bint – n., derogatory synonym for woman appropriated from the Arabic word for daughter or girl. Avoid, on the whole.',
    '6. Blimey, blimey O\'Reilly, cor blimey, gorblimey – n., expression of astonishment. Thought to derive from the phrase "God blind me!" Terribly mild. See also: crikey.',
    '7. Blighter – n., person or thing to be regarded with contempt/envy. See also cad, rotter, swine. Mild.',
    '8. Bloody – adv., intensifier, popularly used in the phrase "Bloody hell!" Very common, medium strength.',
    '9. Blooming – adj., basically a very mild, somewhat archaic form of "bloody". Use with abandon.',
    '10. Bollocks – n., testicles. Used to mean rubbish or nonsense, as in the exclamation of disbelief "Bollocks!" and the album title Never Mind the Bollocks, Here\'s the Sex Pistols; in phrases such as "the dog\'s bollocks" to mean something definitive and perfect; and, in the related word bollocking, a dressing-down ("I gave the useless fool a bollocking"). Medium strength, and very common.',
    '11. Bugger – n., sodomite (i.e. someone who practises buggery); jerk; silly fool. As a verb, can mean to sodomise; to ruin ("You\'ve buggered that up!"); or to tire. Also used as an exclamation of annoyance ("bugger!"); as a milder variant of "fuck" in the phrases "bugger off" and "bugger all"; and, in the phrase, "playing silly buggers", to act the fool. Medium strength. Also very popular in Australia.',
    '12. Cad – n., untrustworthy person to be regarded with contempt/envy. See also blighter, rotter, swine. Mild.',
    '13. Cack – n., shit. Also: Cack-handed – adj, clumsy, inept. A cack-handed execution will often lead to a cock-up. Mild. Use merrily.',
    '14. Chav – n., working-class person with an urban sporty style. Very patronising. Avoid.',
    '15. Cobblers – n., nonsense. Very mild.',
    '16. Cock-up – n., snafu. As a verb, means to screw up drastically. Mild.',
    '17. Codger – n., an old man, often grumpy. Mild.',
    '18. Crikey – n., expression of astonishment. Synonym for Christ.',
    '19. Cunt – n., vagina; an unpleasant or stupid person. Strong, but much less offensive than in the US. Can be used as an adjective in the related word cuntish. Use with care, unless writing a piece based on East End gangsterisms.',
    '20. Dickhead – n., a stupid, irritating person, usually a man. Moderate strength. See also: knob, knobhead, knobber.',
    '21. Duffer – n., elderly idiot. Mild.',
    '22. Feck – milder Irish variant of fuck that caught on in the UK thanks to the \'90s sitcom Father Ted.',
    '23. Git – n., someone who has just beaten you at pool, stolen your spouse, bought the last pasty in the shop, got the job you wanted, or in some other way won one over on you. Mild.',
    '24. Gordon Bennett – n., variant on "Gorblimey!" and the profane outburst "Jesus Christ!" Derives from the Victorian publisher and playboy James Gordon Bennett Jr. Mild.',
    '25. Gormless – adj., dim. Mild.',
    '26. Knob, knobend, knobhead, knobber – n., a stupid, irritating person, usually a man. "Knob" is a synonym for penis. Mild.',
    '27. Manky – adj., worthless, disgusting. Mild.',
    '28. Minger – n., a very unattractive person or thing. Mild.',
    '29. Minging – adj., foul, disgusting, worthless. Mild.',
    '30. Munter – n., unattractive woman. Avoid.',
    '31. Naff – adj., tasteless, crap. Mild.',
    '32. Numpty – n., Scottish idiot. Mild.',
    '33. Nutter – n., crazy person. A synonym for the US "nut". Avoid.',
    '34. Pillock – n., idiot. Mild.',
    '35. Pish – n., Scottish piss.',
    '36. Pissed off – angry, synonym for the US "pissed". Medium strength.',
    '37. Plonker – n., annoying idiot. Immortalised in the \'80s BBC sitcom Only Fools and Horses. Mild.',
    '38. Poxy – adj., riddled with pox; crappy, third-rate. Mild.',
    '39. Prat – n., idiot. Mild.',
    '40. Rotter – n., person to be regarded with contempt/envy. See also blighter, rotter, swine. Mild, unless of course preceded by a strong intensifier, as in Steve Jones\' line: "What a fucking rotter."',
    '41. Scrubber – n., promiscuous woman. Avoid.',
    '42. Shite – n., variant of shit. Moderate. Used in a bewildering variety of constructions, including gobshite, shitehawk, and Steve Coogan\'s Paul Calf catchphrase, "bag o\' shite".',
    '43. Swine – noun, person to be regarded with contempt/envy. See also blighter, cad, rotter, swine. Mild.',
    '44. Taking the piss/Mick/Michael – taking liberties, making fun of. Mild.',
    '45. Tosser – n. masturbator; despicable person. A milder synonym for wanker.',
    '46. Tuss – n, Cornish idiot. Synonym for either penis or "someone from St Just", depending who you ask.',
    '47. Twat – n., vagina; rotter. Milder synonym for cunt. Can also be used as a verb to mean hit ("Watch me while I twat him") or inebriated ("I was twatted"). Use with care.',
    '48. Wally – n., fool. Possibly short for Walter. Terribly mild.',
    '49. Wanker – n., masturbator; despicable person. As a verb, can also mean very inebriated ("I was absolutely wankered"). Strong. See also: tosser.',
]
